### ISSUE TITLE
DisplaySnackBar does database work?

### ISSUE THREAD

**Issue by kenyee** [stevdza-san/To-Do-Compose#1]
https://github.com/stevdza-san/To-Do-Compose/blob/30efd1ec5631ac9a2df7984f4c6e1af21868c4f2/app/src/main/java/com/example/to_docompose/ui/screens/list/ListScreen.kt#L108

Trying to figure out whether this course is useful and noticed this bit of oddness...
DisplaySnackBar calls handleDatabaseActions on every redraw?

**Comment by stevdza-san** [comment]
@kenyee Hey buddy, thanks for your feedback! :)
Obviously I've missed it somehow. Anyway, I'll check it out, provide a fix within a few days and close the issue.

**Comment by kenyee** [comment]
was there a fix for this?  Noticed the issue got closed...but didn't see any code changes...

**Comment by stevdza-san** [comment]
> 
> 
> was there a fix for this? Noticed the issue got closed...but didn't see any code changes...

Yes, check out the branch number 13.

**Comment by kenyee** [comment]
ahh..thx.  hmm..now it does a DB load in ListScreen as a side effect of displaying that composable instead of doing it in DisplaySnackBar 🤔 

Probably should be done in the VM...

**Comment by stevdza-san** [comment]
> 
> 
> ahh..thx. hmm..now it does a DB load in ListScreen as a side effect of displaying that composable instead of doing it in DisplaySnackBar 🤔
> 
> Probably should be done in the VM...

You can call them inside an init block of a view model for example.
